<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<title>@title</title>
<!-- <link rel="shortcut icon" type="image/ico" href="favicon.ico" /> -->
<link rel="stylesheet" href="./lib/layui/css/layui.css" type="text/css">
<link rel="stylesheet" href="./css/common.css">
<!--[if lt IE 9]>
  <script src="/lib/html5shiv.min.js" ></script>
  <script src="/lib/es5.shim.min.js"></script>
  <script src="/lib/respond.min.js"></script>
  <script src="/lib/json3.min.js"></script>
<![endif]-->